/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalProject;

import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;

import java.time.LocalDateTime;

import java.time.format.DateTimeFormatter;

import java.util.Date;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author splimter
 */
public class Checkout extends javax.swing.JFrame {

    /**
     * Creates new form Checkout
     */
    private Client client;
    private String _id, cid;

    public Checkout(String cid) {
        this.cid = cid;
        initComponents();
        this.setLocationRelativeTo(null);
        btnChkout.setEnabled(false);
        try {
            _id = DBMan.getClientFromRoom(Integer.valueOf(cid));
            client = DBMan.getClient(Integer.valueOf(_id)).get(0);
            lblClientName.setText(client.clientName);
            lblClientCIID.setText(client.clientCIID);
            lblReservationDate.setText(client.reservationDate);

            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
            LocalDateTime now = LocalDateTime.now();
            try {
                Date res = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").parse(client.reservationDate);
                Date today = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").parse(dtf.format(now));
                lblDaySpen.setText(String.valueOf((today.getTime() - res.getTime()) / 86400000));
            } catch (ParseException ex) {
                Logger.getLogger(Checkout.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Checkout.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnChkout = new javax.swing.JButton();
        lblClientName = new javax.swing.JLabel();
        lblClientCIID = new javax.swing.JLabel();
        lblReservationDate = new javax.swing.JLabel();
        lblDaySpen = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        txtAddTax = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        txtTypePrice = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Client Name:");

        jLabel2.setText("Cleint CIID:");

        jLabel3.setText("Reservation Date:");

        jLabel4.setText("Day spen:");

        jLabel5.setText("Type Price:");

        jLabel6.setText("Total Price:");

        jLabel7.setText("Additional Tax:");

        btnChkout.setText("Checkout");
        btnChkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChkoutActionPerformed(evt);
            }
        });

        lblClientName.setText("$clientName");

        lblClientCIID.setText("$clientCIID");

        lblReservationDate.setText("$reservationDate");

        lblDaySpen.setText("$DaySpen");

        lblTotalPrice.setText("$TotalPrice");

        txtAddTax.setText("0");
        txtAddTax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddTaxKeyReleased(evt);
            }
        });

        jLabel14.setText("da");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtTypePrice.setText("0");
        txtTypePrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTypePriceKeyReleased(evt);
            }
        });

        jLabel15.setText("da");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChkout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalPrice)
                            .addComponent(lblDaySpen)
                            .addComponent(lblReservationDate)
                            .addComponent(lblClientCIID)
                            .addComponent(lblClientName)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTypePrice, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAddTax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblClientName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblClientCIID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblReservationDate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDaySpen)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTypePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(14, 14, 14)
                        .addComponent(lblTotalPrice)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChkout)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTypePriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTypePriceKeyReleased
        if (!txtTypePrice.getText().equals("") && !txtAddTax.getText().equals("")) {
            btnChkout.setEnabled(true);
        } else {
            btnChkout.setEnabled(false);
        }
        int price = Integer.valueOf(lblDaySpen.getText()) * Integer.valueOf(txtTypePrice.getText()) + Integer.valueOf(txtAddTax.getText());
        lblTotalPrice.setText(String.valueOf(price));
    }//GEN-LAST:event_txtTypePriceKeyReleased

    private void txtAddTaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddTaxKeyReleased
        if (!txtTypePrice.getText().equals("") && !txtAddTax.getText().equals("")) {
            btnChkout.setEnabled(true);
        } else {
            btnChkout.setEnabled(false);
        }
        int price = Integer.valueOf(lblDaySpen.getText()) * Integer.valueOf(txtTypePrice.getText()) + Integer.valueOf(txtAddTax.getText());
        lblTotalPrice.setText(String.valueOf(price));
    }//GEN-LAST:event_txtAddTaxKeyReleased

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnChkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChkoutActionPerformed
        try {
            DBMan.deleteClient(cid, _id);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Checkout.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnChkoutActionPerformed

    public static void main(String cid) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checkout(cid).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChkout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblClientCIID;
    private javax.swing.JLabel lblClientName;
    private javax.swing.JLabel lblDaySpen;
    private javax.swing.JLabel lblReservationDate;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JTextField txtAddTax;
    private javax.swing.JTextField txtTypePrice;
    // End of variables declaration//GEN-END:variables
}
