/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Piano;

import java.io.*;
import java.util.ArrayList;
import java.util.logging.*;
import sun.audio.*;

/**
 *
 * @author splimter
 */
public class Piano extends javax.swing.JFrame {

    ArrayList<InputStream> audio = new ArrayList<>();

    ArrayList<AudioStream> music = new ArrayList<>();

    /**
     * Creates new form Piano
     */
    public Piano() {
        initComponents();
        try {
            initNotes();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    void initNotes() throws FileNotFoundException {

        System.out.println(Piano.class.getResource("/Piano/srcNotes/"));
        audio.add(getClass().getResourceAsStream("/Piano/srcNotes/A.wav"));
        audio.add(getClass().getResourceAsStream("/Piano/srcNotes/B.wav"));
        audio.add(getClass().getResourceAsStream("/Piano/srcNotes/C.wav"));
        audio.add(getClass().getResourceAsStream("/Piano/srcNotes/C_s.wav"));
        audio.add(getClass().getResourceAsStream("/Piano/srcNotes/D.wav"));
        audio.add(getClass().getResourceAsStream("/Piano/srcNotes/D_s.wav"));
        audio.add(getClass().getResourceAsStream("/Piano/srcNotes/E.wav"));
        audio.add(getClass().getResourceAsStream("/Piano/srcNotes/F.wav"));
        audio.add(getClass().getResourceAsStream("/Piano/srcNotes/F_s.wav"));
        audio.add(getClass().getResourceAsStream("/Piano/srcNotes/G.wav"));
        audio.add(getClass().getResourceAsStream("/Piano/srcNotes/G_s.wav"));

        System.out.println(audio);

//        for (int i = 0; i < 12; i++) {
//            try {
//                music.add(new AudioStream(audio.get(i)));
//            } catch (IOException ex) {
//                Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
        audio.forEach((InputStream e) -> {
            try {
                music.add(new AudioStream(e));
            } catch (IOException ex) {
                Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnGs = new javax.swing.JButton();
        btnCs = new javax.swing.JButton();
        btnDs = new javax.swing.JButton();
        btnFs = new javax.swing.JButton();
        btnG = new javax.swing.JButton();
        btnA = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        btnC3 = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 8));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGs.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnGs.setText("G#");
        btnGs.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnGs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGsActionPerformed(evt);
            }
        });
        jPanel2.add(btnGs, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 50, 140));

        btnCs.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnCs.setText("C#");
        btnCs.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCsActionPerformed(evt);
            }
        });
        jPanel2.add(btnCs, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 50, 140));

        btnDs.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnDs.setText("D#");
        btnDs.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnDs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDsActionPerformed(evt);
            }
        });
        jPanel2.add(btnDs, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 50, 140));

        btnFs.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnFs.setText("F#");
        btnFs.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnFs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFsActionPerformed(evt);
            }
        });
        jPanel2.add(btnFs, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 50, 140));

        btnG.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnG.setText("G");
        btnG.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGActionPerformed(evt);
            }
        });
        jPanel2.add(btnG, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 70, 280));

        btnA.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnA.setText("A");
        btnA.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });
        jPanel2.add(btnA, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 70, 280));

        btnB.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnB.setText("B");
        btnB.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });
        jPanel2.add(btnB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 70, 280));

        btnC3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnC3.setText("C");
        btnC3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 70, 280));

        btnD.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnD.setText("D");
        btnD.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDActionPerformed(evt);
            }
        });
        jPanel2.add(btnD, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 70, 280));

        btnE.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnE.setText("E");
        btnE.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });
        jPanel2.add(btnE, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 70, 280));

        btnF.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnF.setText("F");
        btnF.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFActionPerformed(evt);
            }
        });
        jPanel2.add(btnF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 70, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGsActionPerformed
        // TODO add your handling code here:
        AudioPlayer.player.start(music.get(10));
    }//GEN-LAST:event_btnGsActionPerformed

    private void btnGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGActionPerformed
        // TODO add your handling code here:
        AudioPlayer.player.start(music.get(9));

    }//GEN-LAST:event_btnGActionPerformed

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        // TODO add your handling code here:

        AudioPlayer.player.start(music.get(0));
    }//GEN-LAST:event_btnAActionPerformed

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
        // TODO add your handling code here:
        AudioPlayer.player.start(music.get(1));
    }//GEN-LAST:event_btnBActionPerformed

    private void btnC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC3ActionPerformed
        // TODO add your handling code here:
        AudioPlayer.player.start(music.get(2));
    }//GEN-LAST:event_btnC3ActionPerformed

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDActionPerformed
        // TODO add your handling code here:
        AudioPlayer.player.start(music.get(4));
    }//GEN-LAST:event_btnDActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        // TODO add your handling code here:
        AudioPlayer.player.start(music.get(6));
    }//GEN-LAST:event_btnEActionPerformed

    private void btnFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFActionPerformed
        // TODO add your handling code here:
        AudioPlayer.player.start(music.get(7));
    }//GEN-LAST:event_btnFActionPerformed

    private void btnCsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCsActionPerformed
        // TODO add your handling code here:
        AudioPlayer.player.start(music.get(3));
    }//GEN-LAST:event_btnCsActionPerformed

    private void btnDsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDsActionPerformed
        // TODO add your handling code here:
        AudioPlayer.player.start(music.get(5));
    }//GEN-LAST:event_btnDsActionPerformed

    private void btnFsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFsActionPerformed
        // TODO add your handling code here:
        AudioPlayer.player.start(music.get(8));
    }//GEN-LAST:event_btnFsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Piano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnC3;
    private javax.swing.JButton btnCs;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnDs;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnF;
    private javax.swing.JButton btnFs;
    private javax.swing.JButton btnG;
    private javax.swing.JButton btnGs;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
